version: 1
validation: sovereign

default_denom: uwolo

accounts:
  - name: foundercold
    coins:
      - 60000000000000uwolo

  - name: founderoperating
    coins:
      - 5000000000000uwolo

  - name: communitytreasury
    coins:
      - 10000000000000uwolo

  - name: dexliquidity
    coins:
      - 10000000000000uwolo

  - name: faucetgrowth
    coins:
      - 7000000000000uwolo

  - name: validatorops
    coins:
      - 5000000000000uwolo

  - name: ecosystembounties
    coins:
      - 3000000000000uwolo

client:
  openapi:
    path: docs/static/openapi.json

faucet:
  name: faucetgrowth
  coins:
    - 2000000uwolo

validators:
  - name: validatorops
    bonded: 1000000000uwolo