// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wolochain/wartrophy/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryTrophyRequest identifies one trophy.
type QueryTrophyRequest struct {
	TrophyId string `protobuf:"bytes,1,opt,name=trophy_id,json=trophyId,proto3" json:"trophy_id,omitempty"`
}

func (m *QueryTrophyRequest) Reset()         { *m = QueryTrophyRequest{} }
func (m *QueryTrophyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTrophyRequest) ProtoMessage()    {}
func (*QueryTrophyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d940bd98ab69545b, []int{0}
}
func (m *QueryTrophyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTrophyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTrophyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTrophyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTrophyRequest.Merge(m, src)
}
func (m *QueryTrophyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTrophyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTrophyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTrophyRequest proto.InternalMessageInfo

func (m *QueryTrophyRequest) GetTrophyId() string {
	if m != nil {
		return m.TrophyId
	}
	return ""
}

// QueryTrophyResponse contains one trophy.
type QueryTrophyResponse struct {
	Trophy *Trophy `protobuf:"bytes,1,opt,name=trophy,proto3" json:"trophy,omitempty"`
}

func (m *QueryTrophyResponse) Reset()         { *m = QueryTrophyResponse{} }
func (m *QueryTrophyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTrophyResponse) ProtoMessage()    {}
func (*QueryTrophyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d940bd98ab69545b, []int{1}
}
func (m *QueryTrophyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTrophyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTrophyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTrophyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTrophyResponse.Merge(m, src)
}
func (m *QueryTrophyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTrophyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTrophyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTrophyResponse proto.InternalMessageInfo

func (m *QueryTrophyResponse) GetTrophy() *Trophy {
	if m != nil {
		return m.Trophy
	}
	return nil
}

// QueryTrophiesRequest contains pagination options.
type QueryTrophiesRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTrophiesRequest) Reset()         { *m = QueryTrophiesRequest{} }
func (m *QueryTrophiesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTrophiesRequest) ProtoMessage()    {}
func (*QueryTrophiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d940bd98ab69545b, []int{2}
}
func (m *QueryTrophiesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTrophiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTrophiesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTrophiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTrophiesRequest.Merge(m, src)
}
func (m *QueryTrophiesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTrophiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTrophiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTrophiesRequest proto.InternalMessageInfo

func (m *QueryTrophiesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryTrophiesResponse contains a trophy page.
type QueryTrophiesResponse struct {
	Trophies   []Trophy            `protobuf:"bytes,1,rep,name=trophies,proto3" json:"trophies"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTrophiesResponse) Reset()         { *m = QueryTrophiesResponse{} }
func (m *QueryTrophiesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTrophiesResponse) ProtoMessage()    {}
func (*QueryTrophiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d940bd98ab69545b, []int{3}
}
func (m *QueryTrophiesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTrophiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTrophiesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTrophiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTrophiesResponse.Merge(m, src)
}
func (m *QueryTrophiesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTrophiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTrophiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTrophiesResponse proto.InternalMessageInfo

func (m *QueryTrophiesResponse) GetTrophies() []Trophy {
	if m != nil {
		return m.Trophies
	}
	return nil
}

func (m *QueryTrophiesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryTrophyOwnerRequest identifies a trophy.
type QueryTrophyOwnerRequest struct {
	TrophyId string `protobuf:"bytes,1,opt,name=trophy_id,json=trophyId,proto3" json:"trophy_id,omitempty"`
}

func (m *QueryTrophyOwnerRequest) Reset()         { *m = QueryTrophyOwnerRequest{} }
func (m *QueryTrophyOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTrophyOwnerRequest) ProtoMessage()    {}
func (*QueryTrophyOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d940bd98ab69545b, []int{4}
}
func (m *QueryTrophyOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTrophyOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTrophyOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTrophyOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTrophyOwnerRequest.Merge(m, src)
}
func (m *QueryTrophyOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTrophyOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTrophyOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTrophyOwnerRequest proto.InternalMessageInfo

func (m *QueryTrophyOwnerRequest) GetTrophyId() string {
	if m != nil {
		return m.TrophyId
	}
	return ""
}

// QueryTrophyOwnerResponse contains the current owner and lifecycle status.
type QueryTrophyOwnerResponse struct {
	TrophyId string       `protobuf:"bytes,1,opt,name=trophy_id,json=trophyId,proto3" json:"trophy_id,omitempty"`
	Owner    string       `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Status   TrophyStatus `protobuf:"varint,3,opt,name=status,proto3,enum=wolochain.wartrophy.v1.TrophyStatus" json:"status,omitempty"`
}

func (m *QueryTrophyOwnerResponse) Reset()         { *m = QueryTrophyOwnerResponse{} }
func (m *QueryTrophyOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTrophyOwnerResponse) ProtoMessage()    {}
func (*QueryTrophyOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d940bd98ab69545b, []int{5}
}
func (m *QueryTrophyOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTrophyOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTrophyOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTrophyOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTrophyOwnerResponse.Merge(m, src)
}
func (m *QueryTrophyOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTrophyOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTrophyOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTrophyOwnerResponse proto.InternalMessageInfo

func (m *QueryTrophyOwnerResponse) GetTrophyId() string {
	if m != nil {
		return m.TrophyId
	}
	return ""
}

func (m *QueryTrophyOwnerResponse) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *QueryTrophyOwnerResponse) GetStatus() TrophyStatus {
	if m != nil {
		return m.Status
	}
	return TrophyStatus_TROPHY_STATUS_UNSPECIFIED
}

// QueryTrophiesByOwnerRequest identifies an owner and pagination options.
type QueryTrophiesByOwnerRequest struct {
	Owner      string             `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTrophiesByOwnerRequest) Reset()         { *m = QueryTrophiesByOwnerRequest{} }
func (m *QueryTrophiesByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTrophiesByOwnerRequest) ProtoMessage()    {}
func (*QueryTrophiesByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d940bd98ab69545b, []int{6}
}
func (m *QueryTrophiesByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTrophiesByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTrophiesByOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTrophiesByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTrophiesByOwnerRequest.Merge(m, src)
}
func (m *QueryTrophiesByOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTrophiesByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTrophiesByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTrophiesByOwnerRequest proto.InternalMessageInfo

func (m *QueryTrophiesByOwnerRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *QueryTrophiesByOwnerRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryTrophiesByOwnerResponse contains trophies assigned to an owner.
type QueryTrophiesByOwnerResponse struct {
	Trophies   []Trophy            `protobuf:"bytes,1,rep,name=trophies,proto3" json:"trophies"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTrophiesByOwnerResponse) Reset()         { *m = QueryTrophiesByOwnerResponse{} }
func (m *QueryTrophiesByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTrophiesByOwnerResponse) ProtoMessage()    {}
func (*QueryTrophiesByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d940bd98ab69545b, []int{7}
}
func (m *QueryTrophiesByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTrophiesByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTrophiesByOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTrophiesByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTrophiesByOwnerResponse.Merge(m, src)
}
func (m *QueryTrophiesByOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTrophiesByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTrophiesByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTrophiesByOwnerResponse proto.InternalMessageInfo

func (m *QueryTrophiesByOwnerResponse) GetTrophies() []Trophy {
	if m != nil {
		return m.Trophies
	}
	return nil
}

func (m *QueryTrophiesByOwnerResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryTrophyAuthorityRequest requests the current authority.
type QueryTrophyAuthorityRequest struct {
}

func (m *QueryTrophyAuthorityRequest) Reset()         { *m = QueryTrophyAuthorityRequest{} }
func (m *QueryTrophyAuthorityRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTrophyAuthorityRequest) ProtoMessage()    {}
func (*QueryTrophyAuthorityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d940bd98ab69545b, []int{8}
}
func (m *QueryTrophyAuthorityRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTrophyAuthorityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTrophyAuthorityRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTrophyAuthorityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTrophyAuthorityRequest.Merge(m, src)
}
func (m *QueryTrophyAuthorityRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTrophyAuthorityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTrophyAuthorityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTrophyAuthorityRequest proto.InternalMessageInfo

// QueryTrophyAuthorityResponse contains the current authority address.
type QueryTrophyAuthorityResponse struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *QueryTrophyAuthorityResponse) Reset()         { *m = QueryTrophyAuthorityResponse{} }
func (m *QueryTrophyAuthorityResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTrophyAuthorityResponse) ProtoMessage()    {}
func (*QueryTrophyAuthorityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d940bd98ab69545b, []int{9}
}
func (m *QueryTrophyAuthorityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTrophyAuthorityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTrophyAuthorityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTrophyAuthorityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTrophyAuthorityResponse.Merge(m, src)
}
func (m *QueryTrophyAuthorityResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTrophyAuthorityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTrophyAuthorityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTrophyAuthorityResponse proto.InternalMessageInfo

func (m *QueryTrophyAuthorityResponse) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryTrophyRequest)(nil), "wolochain.wartrophy.v1.QueryTrophyRequest")
	proto.RegisterType((*QueryTrophyResponse)(nil), "wolochain.wartrophy.v1.QueryTrophyResponse")
	proto.RegisterType((*QueryTrophiesRequest)(nil), "wolochain.wartrophy.v1.QueryTrophiesRequest")
	proto.RegisterType((*QueryTrophiesResponse)(nil), "wolochain.wartrophy.v1.QueryTrophiesResponse")
	proto.RegisterType((*QueryTrophyOwnerRequest)(nil), "wolochain.wartrophy.v1.QueryTrophyOwnerRequest")
	proto.RegisterType((*QueryTrophyOwnerResponse)(nil), "wolochain.wartrophy.v1.QueryTrophyOwnerResponse")
	proto.RegisterType((*QueryTrophiesByOwnerRequest)(nil), "wolochain.wartrophy.v1.QueryTrophiesByOwnerRequest")
	proto.RegisterType((*QueryTrophiesByOwnerResponse)(nil), "wolochain.wartrophy.v1.QueryTrophiesByOwnerResponse")
	proto.RegisterType((*QueryTrophyAuthorityRequest)(nil), "wolochain.wartrophy.v1.QueryTrophyAuthorityRequest")
	proto.RegisterType((*QueryTrophyAuthorityResponse)(nil), "wolochain.wartrophy.v1.QueryTrophyAuthorityResponse")
}

func init() {
	proto.RegisterFile("wolochain/wartrophy/v1/query.proto", fileDescriptor_d940bd98ab69545b)
}

var fileDescriptor_d940bd98ab69545b = []byte{
	// 687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0x4f, 0x4f, 0x13, 0x41,
	0x18, 0xc6, 0x3b, 0x20, 0x0d, 0x1d, 0x12, 0x4d, 0xc6, 0xaa, 0xb5, 0xe0, 0x5a, 0x17, 0xa3, 0x88,
	0xb0, 0x63, 0x0b, 0xc1, 0xc4, 0x78, 0x90, 0x1e, 0x20, 0x1e, 0x8c, 0x5a, 0x8c, 0x07, 0x0f, 0x92,
	0x29, 0x9d, 0x6c, 0x37, 0x81, 0x9d, 0x65, 0x67, 0x0a, 0x36, 0x84, 0x8b, 0x57, 0x2f, 0x1a, 0x63,
	0xbc, 0x7b, 0x31, 0x26, 0x1e, 0xf5, 0x2b, 0x18, 0x8e, 0x44, 0x2f, 0x9e, 0x8c, 0x01, 0x3f, 0x88,
	0xe9, 0xcc, 0xec, 0x3f, 0x4a, 0xdb, 0xc5, 0x93, 0xa7, 0x76, 0x66, 0x9f, 0xe7, 0x9d, 0xdf, 0x3c,
	0x3b, 0xef, 0x2c, 0x34, 0xb7, 0xd9, 0x3a, 0x5b, 0x6b, 0x12, 0xc7, 0xc5, 0xdb, 0xc4, 0x17, 0x3e,
	0xf3, 0x9a, 0x6d, 0xbc, 0x55, 0xc6, 0x9b, 0x2d, 0xea, 0xb7, 0x2d, 0xcf, 0x67, 0x82, 0xa1, 0xf3,
	0xa1, 0xc6, 0x0a, 0x35, 0xd6, 0x56, 0xb9, 0x38, 0xbd, 0xc6, 0xf8, 0x06, 0xe3, 0xb8, 0x4e, 0x38,
	0x55, 0x06, 0xbc, 0x55, 0xae, 0x53, 0x41, 0xca, 0xd8, 0x23, 0xb6, 0xe3, 0x12, 0xe1, 0x30, 0x57,
	0xd5, 0x28, 0x5e, 0x54, 0xda, 0x55, 0x39, 0xc2, 0x6a, 0xa0, 0x1f, 0xe5, 0x6d, 0x66, 0x33, 0x35,
	0xdf, 0xf9, 0xa7, 0x67, 0x27, 0x6c, 0xc6, 0xec, 0x75, 0x8a, 0x89, 0xe7, 0x60, 0xe2, 0xba, 0x4c,
	0xc8, 0x6a, 0x81, 0x67, 0xb2, 0x07, 0xb6, 0x86, 0x93, 0x22, 0xb3, 0x0c, 0xd1, 0xe3, 0x0e, 0xd5,
	0x13, 0x39, 0x59, 0xa3, 0x9b, 0x2d, 0xca, 0x05, 0x1a, 0x87, 0x39, 0xa5, 0x5a, 0x75, 0x1a, 0x05,
	0x50, 0x02, 0x53, 0xb9, 0xda, 0xa8, 0x9a, 0xb8, 0xdf, 0x30, 0x1f, 0xc0, 0xb3, 0x09, 0x0b, 0xf7,
	0x98, 0xcb, 0x29, 0x5a, 0x80, 0x59, 0x25, 0x91, 0x86, 0xb1, 0x8a, 0x61, 0x1d, 0x1f, 0x89, 0xa5,
	0x7d, 0x5a, 0x6d, 0x3e, 0x87, 0xf9, 0xa8, 0x9c, 0x43, 0x79, 0xc0, 0xb0, 0x04, 0x61, 0x94, 0x90,
	0xae, 0x79, 0xcd, 0xd2, 0xa9, 0x74, 0xe2, 0xb4, 0x54, 0xfe, 0x3a, 0x4e, 0xeb, 0x11, 0xb1, 0xa9,
	0xf6, 0xd6, 0x62, 0x4e, 0xf3, 0x03, 0x80, 0xe7, 0x8e, 0x2c, 0xa0, 0x89, 0xef, 0x41, 0xb5, 0x29,
	0x87, 0xf2, 0x02, 0x28, 0x0d, 0x0f, 0x66, 0xae, 0x9e, 0xda, 0xfb, 0x75, 0x39, 0x53, 0x0b, 0x5d,
	0x68, 0x39, 0xc1, 0x38, 0x24, 0x19, 0xaf, 0x0f, 0x64, 0x54, 0xcb, 0x27, 0x20, 0x17, 0xe0, 0x85,
	0x58, 0xa6, 0x0f, 0xb7, 0x5d, 0xea, 0xa7, 0x7a, 0x17, 0xaf, 0x00, 0x2c, 0x74, 0x1b, 0xf5, 0xfe,
	0xfa, 0x39, 0x51, 0x1e, 0x8e, 0xb0, 0x8e, 0x5a, 0x52, 0xe7, 0x6a, 0x6a, 0x80, 0xee, 0xc2, 0x2c,
	0x17, 0x44, 0xb4, 0x78, 0x61, 0xb8, 0x04, 0xa6, 0x4e, 0x57, 0xae, 0xf6, 0x0f, 0x64, 0x45, 0x6a,
	0x6b, 0xda, 0x63, 0xbe, 0x03, 0x70, 0x3c, 0x11, 0x75, 0x35, 0xb9, 0x15, 0x2b, 0x58, 0x53, 0xc2,
	0x54, 0x0b, 0xdf, 0xbf, 0xcc, 0xe6, 0x75, 0x58, 0x8b, 0x8d, 0x86, 0x4f, 0x39, 0x5f, 0x11, 0xbe,
	0xe3, 0xda, 0x01, 0xcd, 0xd2, 0x31, 0xf1, 0xfe, 0xcb, 0x11, 0xf8, 0x04, 0xe0, 0xc4, 0xf1, 0x5c,
	0xff, 0xdf, 0x49, 0xb8, 0x14, 0x8f, 0xb0, 0xbd, 0xd8, 0x12, 0x4d, 0xe6, 0x3b, 0x22, 0xe8, 0x4c,
	0xf3, 0x69, 0x7c, 0x27, 0xf1, 0xc7, 0x61, 0x17, 0xe6, 0x48, 0x30, 0x39, 0x30, 0xe6, 0x48, 0x5a,
	0xf9, 0x96, 0x85, 0x23, 0xb2, 0x30, 0x7a, 0x0f, 0x60, 0x56, 0x55, 0x47, 0xd3, 0xbd, 0x42, 0xe8,
	0xbe, 0x32, 0x8a, 0x37, 0x53, 0x69, 0x15, 0xa5, 0x39, 0xff, 0xf2, 0xc7, 0x9f, 0xb7, 0x43, 0x16,
	0x9a, 0xc1, 0xfd, 0xee, 0x28, 0x87, 0x72, 0xbc, 0x13, 0x9e, 0xe0, 0x5d, 0xf4, 0x06, 0xc0, 0xd1,
	0xe0, 0x0d, 0xa2, 0x99, 0xc1, 0xeb, 0x45, 0x97, 0x49, 0x71, 0x36, 0xa5, 0x5a, 0xf3, 0x4d, 0x49,
	0x3e, 0x13, 0x95, 0x06, 0xf1, 0xa1, 0xcf, 0x00, 0x8e, 0xc5, 0x7a, 0x0f, 0xe1, 0x14, 0x31, 0xc4,
	0x7b, 0xa2, 0x78, 0x2b, 0xbd, 0x41, 0xc3, 0xdd, 0x91, 0x70, 0xf3, 0xa8, 0x72, 0x92, 0xf0, 0xb0,
	0xea, 0xa8, 0xaf, 0x00, 0x9e, 0x39, 0xd2, 0x04, 0x68, 0x2e, 0x55, 0x36, 0xc9, 0x56, 0x2e, 0xce,
	0x9f, 0xcc, 0xa4, 0xd1, 0x6f, 0x4b, 0xf4, 0x32, 0xc2, 0xbd, 0xd0, 0x25, 0x25, 0xc7, 0x3b, 0xf2,
	0x77, 0x37, 0x8a, 0xf9, 0x63, 0xc0, 0x1d, 0x1d, 0xf9, 0x34, 0xdc, 0x5d, 0xfd, 0x93, 0x86, 0xbb,
	0xbb, 0xab, 0xcc, 0x1b, 0x92, 0x7b, 0x12, 0x5d, 0xe9, 0xc5, 0x1d, 0x36, 0x52, 0x75, 0x79, 0xef,
	0xc0, 0x00, 0xfb, 0x07, 0x06, 0xf8, 0x7d, 0x60, 0x80, 0xd7, 0x87, 0x46, 0x66, 0xff, 0xd0, 0xc8,
	0xfc, 0x3c, 0x34, 0x32, 0xcf, 0x66, 0x6d, 0x47, 0x34, 0x5b, 0x75, 0x6b, 0x8d, 0x6d, 0x60, 0xba,
	0x41, 0x7c, 0xea, 0xc6, 0xaa, 0xbd, 0x88, 0xd5, 0x13, 0x6d, 0x8f, 0xf2, 0x7a, 0x56, 0x7e, 0xa0,
	0xe7, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x09, 0xff, 0x5a, 0x93, 0x7e, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Trophy returns one trophy by identifier.
	Trophy(ctx context.Context, in *QueryTrophyRequest, opts ...grpc.CallOption) (*QueryTrophyResponse, error)
	// Trophies returns all trophies.
	Trophies(ctx context.Context, in *QueryTrophiesRequest, opts ...grpc.CallOption) (*QueryTrophiesResponse, error)
	// TrophyOwner returns the current entitlement owner and status.
	TrophyOwner(ctx context.Context, in *QueryTrophyOwnerRequest, opts ...grpc.CallOption) (*QueryTrophyOwnerResponse, error)
	// TrophiesByOwner returns active trophies assigned to an owner.
	TrophiesByOwner(ctx context.Context, in *QueryTrophiesByOwnerRequest, opts ...grpc.CallOption) (*QueryTrophiesByOwnerResponse, error)
	// TrophyAuthority returns the current authority signer.
	TrophyAuthority(ctx context.Context, in *QueryTrophyAuthorityRequest, opts ...grpc.CallOption) (*QueryTrophyAuthorityResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Trophy(ctx context.Context, in *QueryTrophyRequest, opts ...grpc.CallOption) (*QueryTrophyResponse, error) {
	out := new(QueryTrophyResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Query/Trophy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Trophies(ctx context.Context, in *QueryTrophiesRequest, opts ...grpc.CallOption) (*QueryTrophiesResponse, error) {
	out := new(QueryTrophiesResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Query/Trophies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TrophyOwner(ctx context.Context, in *QueryTrophyOwnerRequest, opts ...grpc.CallOption) (*QueryTrophyOwnerResponse, error) {
	out := new(QueryTrophyOwnerResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Query/TrophyOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TrophiesByOwner(ctx context.Context, in *QueryTrophiesByOwnerRequest, opts ...grpc.CallOption) (*QueryTrophiesByOwnerResponse, error) {
	out := new(QueryTrophiesByOwnerResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Query/TrophiesByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TrophyAuthority(ctx context.Context, in *QueryTrophyAuthorityRequest, opts ...grpc.CallOption) (*QueryTrophyAuthorityResponse, error) {
	out := new(QueryTrophyAuthorityResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Query/TrophyAuthority", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Trophy returns one trophy by identifier.
	Trophy(context.Context, *QueryTrophyRequest) (*QueryTrophyResponse, error)
	// Trophies returns all trophies.
	Trophies(context.Context, *QueryTrophiesRequest) (*QueryTrophiesResponse, error)
	// TrophyOwner returns the current entitlement owner and status.
	TrophyOwner(context.Context, *QueryTrophyOwnerRequest) (*QueryTrophyOwnerResponse, error)
	// TrophiesByOwner returns active trophies assigned to an owner.
	TrophiesByOwner(context.Context, *QueryTrophiesByOwnerRequest) (*QueryTrophiesByOwnerResponse, error)
	// TrophyAuthority returns the current authority signer.
	TrophyAuthority(context.Context, *QueryTrophyAuthorityRequest) (*QueryTrophyAuthorityResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Trophy(ctx context.Context, req *QueryTrophyRequest) (*QueryTrophyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trophy not implemented")
}
func (*UnimplementedQueryServer) Trophies(ctx context.Context, req *QueryTrophiesRequest) (*QueryTrophiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trophies not implemented")
}
func (*UnimplementedQueryServer) TrophyOwner(ctx context.Context, req *QueryTrophyOwnerRequest) (*QueryTrophyOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrophyOwner not implemented")
}
func (*UnimplementedQueryServer) TrophiesByOwner(ctx context.Context, req *QueryTrophiesByOwnerRequest) (*QueryTrophiesByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrophiesByOwner not implemented")
}
func (*UnimplementedQueryServer) TrophyAuthority(ctx context.Context, req *QueryTrophyAuthorityRequest) (*QueryTrophyAuthorityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrophyAuthority not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Trophy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTrophyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Trophy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Query/Trophy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Trophy(ctx, req.(*QueryTrophyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Trophies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTrophiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Trophies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Query/Trophies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Trophies(ctx, req.(*QueryTrophiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TrophyOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTrophyOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TrophyOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Query/TrophyOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TrophyOwner(ctx, req.(*QueryTrophyOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TrophiesByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTrophiesByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TrophiesByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Query/TrophiesByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TrophiesByOwner(ctx, req.(*QueryTrophiesByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TrophyAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTrophyAuthorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TrophyAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Query/TrophyAuthority",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TrophyAuthority(ctx, req.(*QueryTrophyAuthorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wolochain.wartrophy.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Trophy",
			Handler:    _Query_Trophy_Handler,
		},
		{
			MethodName: "Trophies",
			Handler:    _Query_Trophies_Handler,
		},
		{
			MethodName: "TrophyOwner",
			Handler:    _Query_TrophyOwner_Handler,
		},
		{
			MethodName: "TrophiesByOwner",
			Handler:    _Query_TrophiesByOwner_Handler,
		},
		{
			MethodName: "TrophyAuthority",
			Handler:    _Query_TrophyAuthority_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wolochain/wartrophy/v1/query.proto",
}

func (m *QueryTrophyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTrophyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTrophyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TrophyId) > 0 {
		i -= len(m.TrophyId)
		copy(dAtA[i:], m.TrophyId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TrophyId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTrophyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTrophyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTrophyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Trophy != nil {
		{
			size, err := m.Trophy.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTrophiesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTrophiesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTrophiesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTrophiesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTrophiesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTrophiesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Trophies) > 0 {
		for iNdEx := len(m.Trophies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Trophies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryTrophyOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTrophyOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTrophyOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TrophyId) > 0 {
		i -= len(m.TrophyId)
		copy(dAtA[i:], m.TrophyId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TrophyId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTrophyOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTrophyOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTrophyOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TrophyId) > 0 {
		i -= len(m.TrophyId)
		copy(dAtA[i:], m.TrophyId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TrophyId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTrophiesByOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTrophiesByOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTrophiesByOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTrophiesByOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTrophiesByOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTrophiesByOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Trophies) > 0 {
		for iNdEx := len(m.Trophies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Trophies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryTrophyAuthorityRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTrophyAuthorityRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTrophyAuthorityRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTrophyAuthorityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTrophyAuthorityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTrophyAuthorityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryTrophyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TrophyId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTrophyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Trophy != nil {
		l = m.Trophy.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTrophiesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTrophiesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Trophies) > 0 {
		for _, e := range m.Trophies {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTrophyOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TrophyId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTrophyOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TrophyId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	return n
}

func (m *QueryTrophiesByOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTrophiesByOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Trophies) > 0 {
		for _, e := range m.Trophies {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTrophyAuthorityRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTrophyAuthorityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryTrophyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTrophyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTrophyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrophyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrophyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTrophyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTrophyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTrophyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trophy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Trophy == nil {
				m.Trophy = &Trophy{}
			}
			if err := m.Trophy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTrophiesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTrophiesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTrophiesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTrophiesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTrophiesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTrophiesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trophies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Trophies = append(m.Trophies, Trophy{})
			if err := m.Trophies[len(m.Trophies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTrophyOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTrophyOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTrophyOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrophyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrophyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTrophyOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTrophyOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTrophyOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrophyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrophyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= TrophyStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTrophiesByOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTrophiesByOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTrophiesByOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTrophiesByOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTrophiesByOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTrophiesByOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trophies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Trophies = append(m.Trophies, Trophy{})
			if err := m.Trophies[len(m.Trophies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTrophyAuthorityRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTrophyAuthorityRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTrophyAuthorityRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTrophyAuthorityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTrophyAuthorityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTrophyAuthorityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
