// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wolochain/wartrophy/v1/trophy.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// TrophyStatus is the lifecycle state of a Warbound trophy.
type TrophyStatus int32

const (
	// TROPHY_STATUS_UNSPECIFIED is invalid for a stored trophy.
	TrophyStatus_TROPHY_STATUS_UNSPECIFIED TrophyStatus = 0
	// TROPHY_STATUS_DRAFT is registered but not yet minted.
	TrophyStatus_TROPHY_STATUS_DRAFT TrophyStatus = 1
	// TROPHY_STATUS_ACTIVE can be assigned or reassigned by the authority.
	TrophyStatus_TROPHY_STATUS_ACTIVE TrophyStatus = 2
	// TROPHY_STATUS_RETIRED is permanently inactive.
	TrophyStatus_TROPHY_STATUS_RETIRED TrophyStatus = 3
)

var TrophyStatus_name = map[int32]string{
	0: "TROPHY_STATUS_UNSPECIFIED",
	1: "TROPHY_STATUS_DRAFT",
	2: "TROPHY_STATUS_ACTIVE",
	3: "TROPHY_STATUS_RETIRED",
}

var TrophyStatus_value = map[string]int32{
	"TROPHY_STATUS_UNSPECIFIED": 0,
	"TROPHY_STATUS_DRAFT":       1,
	"TROPHY_STATUS_ACTIVE":      2,
	"TROPHY_STATUS_RETIRED":     3,
}

func (x TrophyStatus) String() string {
	return proto.EnumName(TrophyStatus_name, int32(x))
}

func (TrophyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44223d4e2103e79d, []int{0}
}

// Trophy is the chain-side entitlement record for an AoE2WAR Warbound trophy.
//
// In the first implementation pass this is deliberately state-backed rather
// than holder-owned through x/nft. Standard x/nft MsgSend cannot enforce
// class-specific transfer restrictions.
type Trophy struct {
	TrophyId                string       `protobuf:"bytes,1,opt,name=trophy_id,json=trophyId,proto3" json:"trophy_id,omitempty"`
	ClassId                 string       `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	DisplayName             string       `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status                  TrophyStatus `protobuf:"varint,4,opt,name=status,proto3,enum=wolochain.wartrophy.v1.TrophyStatus" json:"status,omitempty"`
	Minted                  bool         `protobuf:"varint,5,opt,name=minted,proto3" json:"minted,omitempty"`
	Owner                   string       `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	MetadataUri             string       `protobuf:"bytes,7,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	ImageUri                string       `protobuf:"bytes,8,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	TributePerDayUwolo      uint64       `protobuf:"varint,9,opt,name=tribute_per_day_uwolo,json=tributePerDayUwolo,proto3" json:"tribute_per_day_uwolo,omitempty"`
	BountyGrowthPerDayUwolo uint64       `protobuf:"varint,10,opt,name=bounty_growth_per_day_uwolo,json=bountyGrowthPerDayUwolo,proto3" json:"bounty_growth_per_day_uwolo,omitempty"`
	CreatedHeight           int64        `protobuf:"varint,11,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	UpdatedHeight           int64        `protobuf:"varint,12,opt,name=updated_height,json=updatedHeight,proto3" json:"updated_height,omitempty"`
}

func (m *Trophy) Reset()         { *m = Trophy{} }
func (m *Trophy) String() string { return proto.CompactTextString(m) }
func (*Trophy) ProtoMessage()    {}
func (*Trophy) Descriptor() ([]byte, []int) {
	return fileDescriptor_44223d4e2103e79d, []int{0}
}
func (m *Trophy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Trophy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Trophy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Trophy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trophy.Merge(m, src)
}
func (m *Trophy) XXX_Size() int {
	return m.Size()
}
func (m *Trophy) XXX_DiscardUnknown() {
	xxx_messageInfo_Trophy.DiscardUnknown(m)
}

var xxx_messageInfo_Trophy proto.InternalMessageInfo

func (m *Trophy) GetTrophyId() string {
	if m != nil {
		return m.TrophyId
	}
	return ""
}

func (m *Trophy) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func (m *Trophy) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Trophy) GetStatus() TrophyStatus {
	if m != nil {
		return m.Status
	}
	return TrophyStatus_TROPHY_STATUS_UNSPECIFIED
}

func (m *Trophy) GetMinted() bool {
	if m != nil {
		return m.Minted
	}
	return false
}

func (m *Trophy) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Trophy) GetMetadataUri() string {
	if m != nil {
		return m.MetadataUri
	}
	return ""
}

func (m *Trophy) GetImageUri() string {
	if m != nil {
		return m.ImageUri
	}
	return ""
}

func (m *Trophy) GetTributePerDayUwolo() uint64 {
	if m != nil {
		return m.TributePerDayUwolo
	}
	return 0
}

func (m *Trophy) GetBountyGrowthPerDayUwolo() uint64 {
	if m != nil {
		return m.BountyGrowthPerDayUwolo
	}
	return 0
}

func (m *Trophy) GetCreatedHeight() int64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *Trophy) GetUpdatedHeight() int64 {
	if m != nil {
		return m.UpdatedHeight
	}
	return 0
}

func init() {
	proto.RegisterEnum("wolochain.wartrophy.v1.TrophyStatus", TrophyStatus_name, TrophyStatus_value)
	proto.RegisterType((*Trophy)(nil), "wolochain.wartrophy.v1.Trophy")
}

func init() {
	proto.RegisterFile("wolochain/wartrophy/v1/trophy.proto", fileDescriptor_44223d4e2103e79d)
}

var fileDescriptor_44223d4e2103e79d = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcb, 0x6a, 0xdb, 0x40,
	0x14, 0x86, 0x3d, 0x71, 0xa2, 0xd8, 0x13, 0x37, 0x98, 0x69, 0x2e, 0x32, 0xa1, 0x42, 0xbd, 0x81,
	0x28, 0x54, 0xc2, 0xed, 0x36, 0x1b, 0x37, 0x56, 0x12, 0x6d, 0x52, 0x23, 0xcb, 0x85, 0x76, 0x33,
	0x8c, 0xad, 0xc1, 0x1a, 0xb0, 0x2e, 0x8c, 0x46, 0x71, 0x45, 0x5f, 0xa2, 0x8f, 0xd5, 0x55, 0xc9,
	0xb2, 0xcb, 0x62, 0xbf, 0x48, 0xd1, 0x8c, 0xea, 0xda, 0x25, 0x3b, 0x9f, 0xff, 0xfb, 0x0e, 0xfe,
	0x47, 0x1c, 0xf8, 0x72, 0x99, 0x2e, 0xd2, 0x59, 0x44, 0x58, 0xe2, 0x2c, 0x09, 0x17, 0x3c, 0xcd,
	0xa2, 0xd2, 0xb9, 0xef, 0x3b, 0xea, 0x97, 0x9d, 0xf1, 0x54, 0xa4, 0xe8, 0x6c, 0x23, 0xd9, 0x1b,
	0xc9, 0xbe, 0xef, 0xbf, 0xf8, 0xd9, 0x84, 0x5a, 0x20, 0x27, 0x74, 0x01, 0xdb, 0x2a, 0xc7, 0x2c,
	0xd4, 0x81, 0x09, 0xac, 0xb6, 0xdf, 0x52, 0x81, 0x17, 0xa2, 0x1e, 0x6c, 0xcd, 0x16, 0x24, 0xcf,
	0x2b, 0xb6, 0x27, 0xd9, 0xa1, 0x9c, 0xbd, 0x10, 0x3d, 0x87, 0x9d, 0x90, 0xe5, 0xd9, 0x82, 0x94,
	0x38, 0x21, 0x31, 0xd5, 0x9b, 0x12, 0x1f, 0xd5, 0xd9, 0x1d, 0x89, 0x29, 0xba, 0x84, 0x5a, 0x2e,
	0x88, 0x28, 0x72, 0x7d, 0xdf, 0x04, 0xd6, 0xf1, 0xbb, 0x57, 0xf6, 0xe3, 0x75, 0x6c, 0x55, 0x65,
	0x2c, 0x5d, 0xbf, 0xde, 0x41, 0x67, 0x50, 0x8b, 0x59, 0x22, 0x68, 0xa8, 0x1f, 0x98, 0xc0, 0x6a,
	0xf9, 0xf5, 0x84, 0x4e, 0xe0, 0x41, 0xba, 0x4c, 0x28, 0xd7, 0x35, 0xf9, 0x8f, 0x6a, 0xa8, 0xea,
	0xc4, 0x54, 0x90, 0x90, 0x08, 0x82, 0x0b, 0xce, 0xf4, 0x43, 0x55, 0xe7, 0x6f, 0x36, 0xe1, 0xac,
	0x7a, 0x29, 0x8b, 0xc9, 0x9c, 0x4a, 0xde, 0x52, 0x2f, 0x95, 0x41, 0x05, 0xfb, 0xf0, 0x54, 0x70,
	0x36, 0x2d, 0x04, 0xc5, 0x19, 0xe5, 0x38, 0x24, 0x25, 0x2e, 0xaa, 0xb6, 0x7a, 0xdb, 0x04, 0xd6,
	0xbe, 0x8f, 0x6a, 0x38, 0xa2, 0x7c, 0x48, 0xca, 0x49, 0x45, 0xd0, 0x25, 0xbc, 0x98, 0xa6, 0x45,
	0x22, 0x4a, 0x3c, 0xe7, 0xe9, 0x52, 0x44, 0xff, 0x2d, 0x42, 0xb9, 0x78, 0xae, 0x94, 0x1b, 0x69,
	0x6c, 0x6f, 0xbf, 0x86, 0xc7, 0x33, 0x4e, 0x89, 0xa0, 0x21, 0x8e, 0x28, 0x9b, 0x47, 0x42, 0x3f,
	0x32, 0x81, 0xd5, 0xf4, 0x9f, 0xd4, 0xe9, 0xad, 0x0c, 0x2b, 0xad, 0xc8, 0xc2, 0x6d, 0xad, 0xa3,
	0xb4, 0x3a, 0x55, 0xda, 0x9b, 0x6f, 0xb0, 0xb3, 0xfd, 0x11, 0xd1, 0x33, 0xd8, 0x0b, 0xfc, 0x8f,
	0xa3, 0xdb, 0xcf, 0x78, 0x1c, 0x0c, 0x82, 0xc9, 0x18, 0x4f, 0xee, 0xc6, 0x23, 0xf7, 0xca, 0xbb,
	0xf6, 0xdc, 0x61, 0xb7, 0x81, 0xce, 0xe1, 0xd3, 0x5d, 0x3c, 0xf4, 0x07, 0xd7, 0x41, 0x17, 0x20,
	0x1d, 0x9e, 0xec, 0x82, 0xc1, 0x55, 0xe0, 0x7d, 0x72, 0xbb, 0x7b, 0xa8, 0x07, 0x4f, 0x77, 0x89,
	0xef, 0x06, 0x9e, 0xef, 0x0e, 0xbb, 0xcd, 0x0f, 0x37, 0x3f, 0x56, 0x06, 0x78, 0x58, 0x19, 0xe0,
	0xf7, 0xca, 0x00, 0xdf, 0xd7, 0x46, 0xe3, 0x61, 0x6d, 0x34, 0x7e, 0xad, 0x8d, 0xc6, 0x97, 0xb7,
	0x73, 0x26, 0xa2, 0x62, 0x6a, 0xcf, 0xd2, 0xd8, 0xa1, 0x31, 0xe1, 0x34, 0x71, 0xfe, 0x9d, 0xed,
	0xd7, 0xad, 0xc3, 0x15, 0x65, 0x46, 0xf3, 0xa9, 0x26, 0xaf, 0xf6, 0xfd, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd2, 0xeb, 0xaa, 0xbf, 0xdc, 0x02, 0x00, 0x00,
}

func (m *Trophy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Trophy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Trophy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedHeight != 0 {
		i = encodeVarintTrophy(dAtA, i, uint64(m.UpdatedHeight))
		i--
		dAtA[i] = 0x60
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintTrophy(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x58
	}
	if m.BountyGrowthPerDayUwolo != 0 {
		i = encodeVarintTrophy(dAtA, i, uint64(m.BountyGrowthPerDayUwolo))
		i--
		dAtA[i] = 0x50
	}
	if m.TributePerDayUwolo != 0 {
		i = encodeVarintTrophy(dAtA, i, uint64(m.TributePerDayUwolo))
		i--
		dAtA[i] = 0x48
	}
	if len(m.ImageUri) > 0 {
		i -= len(m.ImageUri)
		copy(dAtA[i:], m.ImageUri)
		i = encodeVarintTrophy(dAtA, i, uint64(len(m.ImageUri)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.MetadataUri) > 0 {
		i -= len(m.MetadataUri)
		copy(dAtA[i:], m.MetadataUri)
		i = encodeVarintTrophy(dAtA, i, uint64(len(m.MetadataUri)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTrophy(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x32
	}
	if m.Minted {
		i--
		if m.Minted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Status != 0 {
		i = encodeVarintTrophy(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if len(m.DisplayName) > 0 {
		i -= len(m.DisplayName)
		copy(dAtA[i:], m.DisplayName)
		i = encodeVarintTrophy(dAtA, i, uint64(len(m.DisplayName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ClassId) > 0 {
		i -= len(m.ClassId)
		copy(dAtA[i:], m.ClassId)
		i = encodeVarintTrophy(dAtA, i, uint64(len(m.ClassId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TrophyId) > 0 {
		i -= len(m.TrophyId)
		copy(dAtA[i:], m.TrophyId)
		i = encodeVarintTrophy(dAtA, i, uint64(len(m.TrophyId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTrophy(dAtA []byte, offset int, v uint64) int {
	offset -= sovTrophy(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Trophy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TrophyId)
	if l > 0 {
		n += 1 + l + sovTrophy(uint64(l))
	}
	l = len(m.ClassId)
	if l > 0 {
		n += 1 + l + sovTrophy(uint64(l))
	}
	l = len(m.DisplayName)
	if l > 0 {
		n += 1 + l + sovTrophy(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTrophy(uint64(m.Status))
	}
	if m.Minted {
		n += 2
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTrophy(uint64(l))
	}
	l = len(m.MetadataUri)
	if l > 0 {
		n += 1 + l + sovTrophy(uint64(l))
	}
	l = len(m.ImageUri)
	if l > 0 {
		n += 1 + l + sovTrophy(uint64(l))
	}
	if m.TributePerDayUwolo != 0 {
		n += 1 + sovTrophy(uint64(m.TributePerDayUwolo))
	}
	if m.BountyGrowthPerDayUwolo != 0 {
		n += 1 + sovTrophy(uint64(m.BountyGrowthPerDayUwolo))
	}
	if m.CreatedHeight != 0 {
		n += 1 + sovTrophy(uint64(m.CreatedHeight))
	}
	if m.UpdatedHeight != 0 {
		n += 1 + sovTrophy(uint64(m.UpdatedHeight))
	}
	return n
}

func sovTrophy(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTrophy(x uint64) (n int) {
	return sovTrophy(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Trophy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrophy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Trophy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Trophy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrophyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrophy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrophy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrophyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrophy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrophy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrophy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrophy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= TrophyStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Minted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Minted = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrophy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrophy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrophy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrophy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImageUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrophy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrophy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImageUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TributePerDayUwolo", wireType)
			}
			m.TributePerDayUwolo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TributePerDayUwolo |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BountyGrowthPerDayUwolo", wireType)
			}
			m.BountyGrowthPerDayUwolo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BountyGrowthPerDayUwolo |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedHeight", wireType)
			}
			m.UpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTrophy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrophy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTrophy(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTrophy
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrophy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTrophy
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTrophy
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTrophy
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTrophy        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTrophy          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTrophy = fmt.Errorf("proto: unexpected end of group")
)
