// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wolochain/wartrophy/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRegisterTrophy defines a trophy registration request.
type MsgRegisterTrophy struct {
	Authority               string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	TrophyId                string `protobuf:"bytes,2,opt,name=trophy_id,json=trophyId,proto3" json:"trophy_id,omitempty"`
	DisplayName             string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	MetadataUri             string `protobuf:"bytes,4,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	ImageUri                string `protobuf:"bytes,5,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	TributePerDayUwolo      uint64 `protobuf:"varint,6,opt,name=tribute_per_day_uwolo,json=tributePerDayUwolo,proto3" json:"tribute_per_day_uwolo,omitempty"`
	BountyGrowthPerDayUwolo uint64 `protobuf:"varint,7,opt,name=bounty_growth_per_day_uwolo,json=bountyGrowthPerDayUwolo,proto3" json:"bounty_growth_per_day_uwolo,omitempty"`
}

func (m *MsgRegisterTrophy) Reset()         { *m = MsgRegisterTrophy{} }
func (m *MsgRegisterTrophy) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterTrophy) ProtoMessage()    {}
func (*MsgRegisterTrophy) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{0}
}
func (m *MsgRegisterTrophy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterTrophy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterTrophy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterTrophy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterTrophy.Merge(m, src)
}
func (m *MsgRegisterTrophy) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterTrophy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterTrophy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterTrophy proto.InternalMessageInfo

func (m *MsgRegisterTrophy) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRegisterTrophy) GetTrophyId() string {
	if m != nil {
		return m.TrophyId
	}
	return ""
}

func (m *MsgRegisterTrophy) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *MsgRegisterTrophy) GetMetadataUri() string {
	if m != nil {
		return m.MetadataUri
	}
	return ""
}

func (m *MsgRegisterTrophy) GetImageUri() string {
	if m != nil {
		return m.ImageUri
	}
	return ""
}

func (m *MsgRegisterTrophy) GetTributePerDayUwolo() uint64 {
	if m != nil {
		return m.TributePerDayUwolo
	}
	return 0
}

func (m *MsgRegisterTrophy) GetBountyGrowthPerDayUwolo() uint64 {
	if m != nil {
		return m.BountyGrowthPerDayUwolo
	}
	return 0
}

// MsgRegisterTrophyResponse is returned after registration.
type MsgRegisterTrophyResponse struct {
}

func (m *MsgRegisterTrophyResponse) Reset()         { *m = MsgRegisterTrophyResponse{} }
func (m *MsgRegisterTrophyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterTrophyResponse) ProtoMessage()    {}
func (*MsgRegisterTrophyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{1}
}
func (m *MsgRegisterTrophyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterTrophyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterTrophyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterTrophyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterTrophyResponse.Merge(m, src)
}
func (m *MsgRegisterTrophyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterTrophyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterTrophyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterTrophyResponse proto.InternalMessageInfo

// MsgMintTrophy defines a trophy activation request.
type MsgMintTrophy struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	TrophyId  string `protobuf:"bytes,2,opt,name=trophy_id,json=trophyId,proto3" json:"trophy_id,omitempty"`
}

func (m *MsgMintTrophy) Reset()         { *m = MsgMintTrophy{} }
func (m *MsgMintTrophy) String() string { return proto.CompactTextString(m) }
func (*MsgMintTrophy) ProtoMessage()    {}
func (*MsgMintTrophy) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{2}
}
func (m *MsgMintTrophy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMintTrophy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMintTrophy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMintTrophy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintTrophy.Merge(m, src)
}
func (m *MsgMintTrophy) XXX_Size() int {
	return m.Size()
}
func (m *MsgMintTrophy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintTrophy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintTrophy proto.InternalMessageInfo

func (m *MsgMintTrophy) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgMintTrophy) GetTrophyId() string {
	if m != nil {
		return m.TrophyId
	}
	return ""
}

// MsgMintTrophyResponse is returned after minting.
type MsgMintTrophyResponse struct {
}

func (m *MsgMintTrophyResponse) Reset()         { *m = MsgMintTrophyResponse{} }
func (m *MsgMintTrophyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMintTrophyResponse) ProtoMessage()    {}
func (*MsgMintTrophyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{3}
}
func (m *MsgMintTrophyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMintTrophyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMintTrophyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMintTrophyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintTrophyResponse.Merge(m, src)
}
func (m *MsgMintTrophyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMintTrophyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintTrophyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintTrophyResponse proto.InternalMessageInfo

// MsgAssignTrophy defines an initial assignment request.
type MsgAssignTrophy struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	TrophyId  string `protobuf:"bytes,2,opt,name=trophy_id,json=trophyId,proto3" json:"trophy_id,omitempty"`
	Owner     string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *MsgAssignTrophy) Reset()         { *m = MsgAssignTrophy{} }
func (m *MsgAssignTrophy) String() string { return proto.CompactTextString(m) }
func (*MsgAssignTrophy) ProtoMessage()    {}
func (*MsgAssignTrophy) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{4}
}
func (m *MsgAssignTrophy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAssignTrophy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAssignTrophy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAssignTrophy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAssignTrophy.Merge(m, src)
}
func (m *MsgAssignTrophy) XXX_Size() int {
	return m.Size()
}
func (m *MsgAssignTrophy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAssignTrophy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAssignTrophy proto.InternalMessageInfo

func (m *MsgAssignTrophy) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgAssignTrophy) GetTrophyId() string {
	if m != nil {
		return m.TrophyId
	}
	return ""
}

func (m *MsgAssignTrophy) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

// MsgAssignTrophyResponse is returned after assignment.
type MsgAssignTrophyResponse struct {
}

func (m *MsgAssignTrophyResponse) Reset()         { *m = MsgAssignTrophyResponse{} }
func (m *MsgAssignTrophyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAssignTrophyResponse) ProtoMessage()    {}
func (*MsgAssignTrophyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{5}
}
func (m *MsgAssignTrophyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAssignTrophyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAssignTrophyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAssignTrophyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAssignTrophyResponse.Merge(m, src)
}
func (m *MsgAssignTrophyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAssignTrophyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAssignTrophyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAssignTrophyResponse proto.InternalMessageInfo

// MsgReassignTrophy defines an authority-controlled reassignment request.
type MsgReassignTrophy struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	TrophyId  string `protobuf:"bytes,2,opt,name=trophy_id,json=trophyId,proto3" json:"trophy_id,omitempty"`
	NewOwner  string `protobuf:"bytes,3,opt,name=new_owner,json=newOwner,proto3" json:"new_owner,omitempty"`
}

func (m *MsgReassignTrophy) Reset()         { *m = MsgReassignTrophy{} }
func (m *MsgReassignTrophy) String() string { return proto.CompactTextString(m) }
func (*MsgReassignTrophy) ProtoMessage()    {}
func (*MsgReassignTrophy) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{6}
}
func (m *MsgReassignTrophy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgReassignTrophy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgReassignTrophy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgReassignTrophy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReassignTrophy.Merge(m, src)
}
func (m *MsgReassignTrophy) XXX_Size() int {
	return m.Size()
}
func (m *MsgReassignTrophy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReassignTrophy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReassignTrophy proto.InternalMessageInfo

func (m *MsgReassignTrophy) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgReassignTrophy) GetTrophyId() string {
	if m != nil {
		return m.TrophyId
	}
	return ""
}

func (m *MsgReassignTrophy) GetNewOwner() string {
	if m != nil {
		return m.NewOwner
	}
	return ""
}

// MsgReassignTrophyResponse is returned after reassignment.
type MsgReassignTrophyResponse struct {
}

func (m *MsgReassignTrophyResponse) Reset()         { *m = MsgReassignTrophyResponse{} }
func (m *MsgReassignTrophyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgReassignTrophyResponse) ProtoMessage()    {}
func (*MsgReassignTrophyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{7}
}
func (m *MsgReassignTrophyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgReassignTrophyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgReassignTrophyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgReassignTrophyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReassignTrophyResponse.Merge(m, src)
}
func (m *MsgReassignTrophyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgReassignTrophyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReassignTrophyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReassignTrophyResponse proto.InternalMessageInfo

// MsgRetireTrophy defines a permanent retirement request.
type MsgRetireTrophy struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	TrophyId  string `protobuf:"bytes,2,opt,name=trophy_id,json=trophyId,proto3" json:"trophy_id,omitempty"`
}

func (m *MsgRetireTrophy) Reset()         { *m = MsgRetireTrophy{} }
func (m *MsgRetireTrophy) String() string { return proto.CompactTextString(m) }
func (*MsgRetireTrophy) ProtoMessage()    {}
func (*MsgRetireTrophy) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{8}
}
func (m *MsgRetireTrophy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRetireTrophy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRetireTrophy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRetireTrophy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRetireTrophy.Merge(m, src)
}
func (m *MsgRetireTrophy) XXX_Size() int {
	return m.Size()
}
func (m *MsgRetireTrophy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRetireTrophy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRetireTrophy proto.InternalMessageInfo

func (m *MsgRetireTrophy) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRetireTrophy) GetTrophyId() string {
	if m != nil {
		return m.TrophyId
	}
	return ""
}

// MsgRetireTrophyResponse is returned after retirement.
type MsgRetireTrophyResponse struct {
}

func (m *MsgRetireTrophyResponse) Reset()         { *m = MsgRetireTrophyResponse{} }
func (m *MsgRetireTrophyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRetireTrophyResponse) ProtoMessage()    {}
func (*MsgRetireTrophyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{9}
}
func (m *MsgRetireTrophyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRetireTrophyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRetireTrophyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRetireTrophyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRetireTrophyResponse.Merge(m, src)
}
func (m *MsgRetireTrophyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRetireTrophyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRetireTrophyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRetireTrophyResponse proto.InternalMessageInfo

// MsgUpdateTrophyMetadata defines a metadata update request.
type MsgUpdateTrophyMetadata struct {
	Authority   string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	TrophyId    string `protobuf:"bytes,2,opt,name=trophy_id,json=trophyId,proto3" json:"trophy_id,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	MetadataUri string `protobuf:"bytes,4,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	ImageUri    string `protobuf:"bytes,5,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
}

func (m *MsgUpdateTrophyMetadata) Reset()         { *m = MsgUpdateTrophyMetadata{} }
func (m *MsgUpdateTrophyMetadata) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateTrophyMetadata) ProtoMessage()    {}
func (*MsgUpdateTrophyMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{10}
}
func (m *MsgUpdateTrophyMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateTrophyMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateTrophyMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateTrophyMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateTrophyMetadata.Merge(m, src)
}
func (m *MsgUpdateTrophyMetadata) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateTrophyMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateTrophyMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateTrophyMetadata proto.InternalMessageInfo

func (m *MsgUpdateTrophyMetadata) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateTrophyMetadata) GetTrophyId() string {
	if m != nil {
		return m.TrophyId
	}
	return ""
}

func (m *MsgUpdateTrophyMetadata) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *MsgUpdateTrophyMetadata) GetMetadataUri() string {
	if m != nil {
		return m.MetadataUri
	}
	return ""
}

func (m *MsgUpdateTrophyMetadata) GetImageUri() string {
	if m != nil {
		return m.ImageUri
	}
	return ""
}

// MsgUpdateTrophyMetadataResponse is returned after a metadata update.
type MsgUpdateTrophyMetadataResponse struct {
}

func (m *MsgUpdateTrophyMetadataResponse) Reset()         { *m = MsgUpdateTrophyMetadataResponse{} }
func (m *MsgUpdateTrophyMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateTrophyMetadataResponse) ProtoMessage()    {}
func (*MsgUpdateTrophyMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{11}
}
func (m *MsgUpdateTrophyMetadataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateTrophyMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateTrophyMetadataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateTrophyMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateTrophyMetadataResponse.Merge(m, src)
}
func (m *MsgUpdateTrophyMetadataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateTrophyMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateTrophyMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateTrophyMetadataResponse proto.InternalMessageInfo

// MsgSetTrophyAuthority defines an authority rotation request.
type MsgSetTrophyAuthority struct {
	Authority    string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	NewAuthority string `protobuf:"bytes,2,opt,name=new_authority,json=newAuthority,proto3" json:"new_authority,omitempty"`
}

func (m *MsgSetTrophyAuthority) Reset()         { *m = MsgSetTrophyAuthority{} }
func (m *MsgSetTrophyAuthority) String() string { return proto.CompactTextString(m) }
func (*MsgSetTrophyAuthority) ProtoMessage()    {}
func (*MsgSetTrophyAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{12}
}
func (m *MsgSetTrophyAuthority) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetTrophyAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetTrophyAuthority.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetTrophyAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetTrophyAuthority.Merge(m, src)
}
func (m *MsgSetTrophyAuthority) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetTrophyAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetTrophyAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetTrophyAuthority proto.InternalMessageInfo

func (m *MsgSetTrophyAuthority) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetTrophyAuthority) GetNewAuthority() string {
	if m != nil {
		return m.NewAuthority
	}
	return ""
}

// MsgSetTrophyAuthorityResponse is returned after authority rotation.
type MsgSetTrophyAuthorityResponse struct {
}

func (m *MsgSetTrophyAuthorityResponse) Reset()         { *m = MsgSetTrophyAuthorityResponse{} }
func (m *MsgSetTrophyAuthorityResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetTrophyAuthorityResponse) ProtoMessage()    {}
func (*MsgSetTrophyAuthorityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4baab7aff8b19f2, []int{13}
}
func (m *MsgSetTrophyAuthorityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetTrophyAuthorityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetTrophyAuthorityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetTrophyAuthorityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetTrophyAuthorityResponse.Merge(m, src)
}
func (m *MsgSetTrophyAuthorityResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetTrophyAuthorityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetTrophyAuthorityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetTrophyAuthorityResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterTrophy)(nil), "wolochain.wartrophy.v1.MsgRegisterTrophy")
	proto.RegisterType((*MsgRegisterTrophyResponse)(nil), "wolochain.wartrophy.v1.MsgRegisterTrophyResponse")
	proto.RegisterType((*MsgMintTrophy)(nil), "wolochain.wartrophy.v1.MsgMintTrophy")
	proto.RegisterType((*MsgMintTrophyResponse)(nil), "wolochain.wartrophy.v1.MsgMintTrophyResponse")
	proto.RegisterType((*MsgAssignTrophy)(nil), "wolochain.wartrophy.v1.MsgAssignTrophy")
	proto.RegisterType((*MsgAssignTrophyResponse)(nil), "wolochain.wartrophy.v1.MsgAssignTrophyResponse")
	proto.RegisterType((*MsgReassignTrophy)(nil), "wolochain.wartrophy.v1.MsgReassignTrophy")
	proto.RegisterType((*MsgReassignTrophyResponse)(nil), "wolochain.wartrophy.v1.MsgReassignTrophyResponse")
	proto.RegisterType((*MsgRetireTrophy)(nil), "wolochain.wartrophy.v1.MsgRetireTrophy")
	proto.RegisterType((*MsgRetireTrophyResponse)(nil), "wolochain.wartrophy.v1.MsgRetireTrophyResponse")
	proto.RegisterType((*MsgUpdateTrophyMetadata)(nil), "wolochain.wartrophy.v1.MsgUpdateTrophyMetadata")
	proto.RegisterType((*MsgUpdateTrophyMetadataResponse)(nil), "wolochain.wartrophy.v1.MsgUpdateTrophyMetadataResponse")
	proto.RegisterType((*MsgSetTrophyAuthority)(nil), "wolochain.wartrophy.v1.MsgSetTrophyAuthority")
	proto.RegisterType((*MsgSetTrophyAuthorityResponse)(nil), "wolochain.wartrophy.v1.MsgSetTrophyAuthorityResponse")
}

func init() { proto.RegisterFile("wolochain/wartrophy/v1/tx.proto", fileDescriptor_d4baab7aff8b19f2) }

var fileDescriptor_d4baab7aff8b19f2 = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xbd, 0x6e, 0x13, 0x4b,
	0x14, 0xce, 0x3a, 0x3f, 0x37, 0x9e, 0x9b, 0xdc, 0xab, 0xac, 0x92, 0x6b, 0x7b, 0xad, 0x6b, 0x27,
	0x96, 0x50, 0x82, 0x45, 0x76, 0xe5, 0x40, 0x40, 0xb2, 0xa0, 0x48, 0x84, 0x14, 0x51, 0x18, 0x90,
	0x43, 0x1a, 0x9a, 0xd5, 0x38, 0x3b, 0x5a, 0x8f, 0x94, 0x9d, 0xb1, 0x66, 0xc6, 0x71, 0x96, 0x2a,
	0xa2, 0x41, 0xa2, 0x4a, 0xc1, 0x1b, 0xf0, 0x02, 0x29, 0x78, 0x02, 0x44, 0x41, 0x47, 0x44, 0x45,
	0x89, 0x92, 0x22, 0x0d, 0x0f, 0x81, 0xf6, 0xc7, 0xfb, 0x93, 0x5d, 0x36, 0x0e, 0x92, 0x0b, 0x1a,
	0x4b, 0x3e, 0xdf, 0x77, 0x7e, 0xbe, 0x33, 0x67, 0xce, 0x0e, 0xa8, 0x0e, 0xe8, 0x01, 0xdd, 0xef,
	0x42, 0x4c, 0xb4, 0x01, 0x64, 0x82, 0xd1, 0x5e, 0xd7, 0xd6, 0x0e, 0x1b, 0x9a, 0x38, 0x52, 0x7b,
	0x8c, 0x0a, 0x2a, 0xff, 0x17, 0x10, 0xd4, 0x80, 0xa0, 0x1e, 0x36, 0x94, 0x05, 0x68, 0x61, 0x42,
	0x35, 0xf7, 0xd7, 0xa3, 0x2a, 0x85, 0x7d, 0xca, 0x2d, 0xca, 0x35, 0x8b, 0x9b, 0x4e, 0x08, 0x8b,
	0x9b, 0x3e, 0x50, 0xf2, 0x00, 0xdd, 0xfd, 0xa7, 0x79, 0x7f, 0x3c, 0xa8, 0xf6, 0x23, 0x07, 0x16,
	0x5a, 0xdc, 0x6c, 0x23, 0x13, 0x73, 0x81, 0xd8, 0x0b, 0x37, 0xbe, 0x7c, 0x1f, 0xe4, 0x61, 0x5f,
	0x74, 0x29, 0xc3, 0xc2, 0x2e, 0x4a, 0xcb, 0xd2, 0x5a, 0x7e, 0xbb, 0xf8, 0xf5, 0xc3, 0xfa, 0xa2,
	0xef, 0xba, 0x65, 0x18, 0x0c, 0x71, 0xbe, 0x2b, 0x18, 0x26, 0x66, 0x3b, 0xa4, 0xca, 0x65, 0x90,
	0xf7, 0x2a, 0xd4, 0xb1, 0x51, 0xcc, 0x39, 0x7e, 0xed, 0x59, 0xcf, 0xf0, 0xc4, 0x90, 0x57, 0xc0,
	0x9c, 0x81, 0x79, 0xef, 0x00, 0xda, 0x3a, 0x81, 0x16, 0x2a, 0x4e, 0xba, 0xf8, 0xdf, 0xbe, 0xed,
	0x29, 0xb4, 0x90, 0x43, 0xb1, 0x90, 0x80, 0x06, 0x14, 0x50, 0xef, 0x33, 0x5c, 0x9c, 0xf2, 0x28,
	0x43, 0xdb, 0x1e, 0xc3, 0x4e, 0x0a, 0x6c, 0x41, 0x13, 0xb9, 0xf8, 0xb4, 0x97, 0xc2, 0x35, 0x38,
	0x60, 0x03, 0x2c, 0x09, 0x86, 0x3b, 0x7d, 0x81, 0xf4, 0x1e, 0x62, 0xba, 0x01, 0x6d, 0xbd, 0xef,
	0xf4, 0xaf, 0x38, 0xb3, 0x2c, 0xad, 0x4d, 0xb5, 0x65, 0x1f, 0x7c, 0x8e, 0xd8, 0x63, 0x68, 0xef,
	0x39, 0x88, 0xfc, 0x10, 0x94, 0x3b, 0xb4, 0x4f, 0x84, 0xad, 0x9b, 0x8c, 0x0e, 0x44, 0xf7, 0x8a,
	0xe3, 0x5f, 0xae, 0x63, 0xc1, 0xa3, 0xec, 0xb8, 0x8c, 0x88, 0x77, 0x53, 0x7d, 0x7d, 0x79, 0x5a,
	0x0f, 0x1b, 0xf0, 0xf6, 0xf2, 0xb4, 0x5e, 0x0e, 0xcf, 0x31, 0xd1, 0xd8, 0x5a, 0x19, 0x94, 0x12,
	0xc6, 0x36, 0xe2, 0x3d, 0x4a, 0x38, 0xaa, 0x9d, 0x48, 0x60, 0xbe, 0xc5, 0xcd, 0x16, 0x26, 0x62,
	0x8c, 0xe7, 0xd0, 0xac, 0x27, 0x6b, 0x2e, 0xc4, 0x6a, 0x0e, 0x0b, 0xa8, 0x15, 0xc0, 0x52, 0xcc,
	0x10, 0xd4, 0xfa, 0x49, 0x02, 0xff, 0xb6, 0xb8, 0xb9, 0xc5, 0x39, 0x36, 0xc9, 0x38, 0xa7, 0x46,
	0x05, 0xd3, 0x74, 0x40, 0x10, 0xf3, 0xc6, 0x25, 0x23, 0xa0, 0x47, 0x6b, 0xde, 0x49, 0xaa, 0x2b,
	0xc5, 0xd4, 0x45, 0x4b, 0xae, 0x95, 0x40, 0xe1, 0x8a, 0x29, 0x50, 0xf8, 0x45, 0xf2, 0x6f, 0x06,
	0x1c, 0xbb, 0xc6, 0x4d, 0x90, 0x27, 0x68, 0xa0, 0x8f, 0xa6, 0x73, 0x96, 0xa0, 0xc1, 0x33, 0x57,
	0xea, 0x08, 0xc3, 0x17, 0xad, 0x3d, 0x18, 0x3e, 0x98, 0x26, 0xf7, 0x9d, 0x77, 0xa0, 0x6d, 0x24,
	0x30, 0x43, 0xe3, 0x1c, 0xbf, 0x6b, 0x0f, 0x28, 0x5a, 0x82, 0x7f, 0x40, 0x51, 0x53, 0x50, 0xf1,
	0x9b, 0x9c, 0x8b, 0xed, 0xf5, 0x0c, 0x28, 0x7c, 0xac, 0xe5, 0x2f, 0x8a, 0x3f, 0x75, 0x81, 0x35,
	0xef, 0x25, 0x9b, 0xb3, 0x12, 0x6b, 0x4e, 0x9a, 0xda, 0xda, 0x0a, 0xa8, 0xfe, 0x02, 0x0a, 0x9a,
	0xf5, 0x51, 0x72, 0x6f, 0xf2, 0x2e, 0xf2, 0x2f, 0xf2, 0x56, 0x20, 0xf9, 0x77, 0x5b, 0xf5, 0x08,
	0xcc, 0x3b, 0x43, 0x1b, 0xfa, 0xe6, 0xae, 0xf1, 0x9d, 0x23, 0x68, 0x10, 0xa4, 0x6d, 0x6e, 0x24,
	0x95, 0x56, 0x63, 0x4a, 0x93, 0xa5, 0xd6, 0xaa, 0xe0, 0xff, 0x54, 0x60, 0xa8, 0x72, 0xe3, 0xfd,
	0x0c, 0x98, 0x6c, 0x71, 0x53, 0x26, 0xe0, 0x9f, 0x2b, 0x5f, 0xb4, 0xdb, 0x6a, 0xfa, 0x77, 0x54,
	0x4d, 0xac, 0x63, 0xa5, 0x31, 0x32, 0x75, 0x98, 0x57, 0xee, 0x00, 0x10, 0xd9, 0xda, 0xb7, 0x32,
	0x02, 0x84, 0x34, 0x65, 0x7d, 0x24, 0x5a, 0x90, 0xa3, 0x0b, 0xe6, 0x62, 0xdb, 0x76, 0x35, 0xc3,
	0x3d, 0x4a, 0x54, 0xb4, 0x11, 0x89, 0x41, 0x26, 0xb7, 0x7b, 0xb1, 0xad, 0x97, 0xdd, 0xbd, 0x28,
	0xf5, 0x9a, 0xee, 0xa5, 0xad, 0x1e, 0x47, 0x59, 0x6c, 0xed, 0xac, 0x66, 0x86, 0x08, 0x89, 0x99,
	0xca, 0xd2, 0x56, 0x86, 0x7c, 0x2c, 0x81, 0xc5, 0xd4, 0x7d, 0x91, 0x15, 0x29, 0xcd, 0x41, 0x79,
	0x70, 0x43, 0x87, 0xa0, 0x84, 0x57, 0x40, 0x4e, 0xb9, 0x84, 0x59, 0xb3, 0x90, 0xa4, 0x2b, 0x9b,
	0x37, 0xa2, 0x0f, 0x73, 0x2b, 0xd3, 0xc7, 0x97, 0xa7, 0x75, 0x69, 0x7b, 0xe7, 0xf3, 0x79, 0x45,
	0x3a, 0x3b, 0xaf, 0x48, 0xdf, 0xcf, 0x2b, 0xd2, 0xc9, 0x45, 0x65, 0xe2, 0xec, 0xa2, 0x32, 0xf1,
	0xed, 0xa2, 0x32, 0xf1, 0x72, 0xdd, 0xc4, 0xa2, 0xdb, 0xef, 0xa8, 0xfb, 0xd4, 0xd2, 0x90, 0x05,
	0x19, 0x22, 0x5a, 0xf8, 0x3e, 0x3d, 0x8a, 0xbc, 0x50, 0x85, 0xdd, 0x43, 0xbc, 0x33, 0xe3, 0xbe,
	0x21, 0xef, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x07, 0xae, 0x4a, 0x83, 0xc5, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterTrophy creates a draft trophy definition.
	RegisterTrophy(ctx context.Context, in *MsgRegisterTrophy, opts ...grpc.CallOption) (*MsgRegisterTrophyResponse, error)
	// MintTrophy activates a registered trophy.
	MintTrophy(ctx context.Context, in *MsgMintTrophy, opts ...grpc.CallOption) (*MsgMintTrophyResponse, error)
	// AssignTrophy assigns a vacant active trophy.
	AssignTrophy(ctx context.Context, in *MsgAssignTrophy, opts ...grpc.CallOption) (*MsgAssignTrophyResponse, error)
	// ReassignTrophy moves entitlement between holders.
	ReassignTrophy(ctx context.Context, in *MsgReassignTrophy, opts ...grpc.CallOption) (*MsgReassignTrophyResponse, error)
	// RetireTrophy permanently retires a trophy and clears its owner.
	RetireTrophy(ctx context.Context, in *MsgRetireTrophy, opts ...grpc.CallOption) (*MsgRetireTrophyResponse, error)
	// UpdateTrophyMetadata changes display and URI metadata.
	UpdateTrophyMetadata(ctx context.Context, in *MsgUpdateTrophyMetadata, opts ...grpc.CallOption) (*MsgUpdateTrophyMetadataResponse, error)
	// SetTrophyAuthority rotates the authority signer.
	SetTrophyAuthority(ctx context.Context, in *MsgSetTrophyAuthority, opts ...grpc.CallOption) (*MsgSetTrophyAuthorityResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterTrophy(ctx context.Context, in *MsgRegisterTrophy, opts ...grpc.CallOption) (*MsgRegisterTrophyResponse, error) {
	out := new(MsgRegisterTrophyResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Msg/RegisterTrophy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MintTrophy(ctx context.Context, in *MsgMintTrophy, opts ...grpc.CallOption) (*MsgMintTrophyResponse, error) {
	out := new(MsgMintTrophyResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Msg/MintTrophy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AssignTrophy(ctx context.Context, in *MsgAssignTrophy, opts ...grpc.CallOption) (*MsgAssignTrophyResponse, error) {
	out := new(MsgAssignTrophyResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Msg/AssignTrophy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ReassignTrophy(ctx context.Context, in *MsgReassignTrophy, opts ...grpc.CallOption) (*MsgReassignTrophyResponse, error) {
	out := new(MsgReassignTrophyResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Msg/ReassignTrophy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RetireTrophy(ctx context.Context, in *MsgRetireTrophy, opts ...grpc.CallOption) (*MsgRetireTrophyResponse, error) {
	out := new(MsgRetireTrophyResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Msg/RetireTrophy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateTrophyMetadata(ctx context.Context, in *MsgUpdateTrophyMetadata, opts ...grpc.CallOption) (*MsgUpdateTrophyMetadataResponse, error) {
	out := new(MsgUpdateTrophyMetadataResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Msg/UpdateTrophyMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetTrophyAuthority(ctx context.Context, in *MsgSetTrophyAuthority, opts ...grpc.CallOption) (*MsgSetTrophyAuthorityResponse, error) {
	out := new(MsgSetTrophyAuthorityResponse)
	err := c.cc.Invoke(ctx, "/wolochain.wartrophy.v1.Msg/SetTrophyAuthority", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterTrophy creates a draft trophy definition.
	RegisterTrophy(context.Context, *MsgRegisterTrophy) (*MsgRegisterTrophyResponse, error)
	// MintTrophy activates a registered trophy.
	MintTrophy(context.Context, *MsgMintTrophy) (*MsgMintTrophyResponse, error)
	// AssignTrophy assigns a vacant active trophy.
	AssignTrophy(context.Context, *MsgAssignTrophy) (*MsgAssignTrophyResponse, error)
	// ReassignTrophy moves entitlement between holders.
	ReassignTrophy(context.Context, *MsgReassignTrophy) (*MsgReassignTrophyResponse, error)
	// RetireTrophy permanently retires a trophy and clears its owner.
	RetireTrophy(context.Context, *MsgRetireTrophy) (*MsgRetireTrophyResponse, error)
	// UpdateTrophyMetadata changes display and URI metadata.
	UpdateTrophyMetadata(context.Context, *MsgUpdateTrophyMetadata) (*MsgUpdateTrophyMetadataResponse, error)
	// SetTrophyAuthority rotates the authority signer.
	SetTrophyAuthority(context.Context, *MsgSetTrophyAuthority) (*MsgSetTrophyAuthorityResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterTrophy(ctx context.Context, req *MsgRegisterTrophy) (*MsgRegisterTrophyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTrophy not implemented")
}
func (*UnimplementedMsgServer) MintTrophy(ctx context.Context, req *MsgMintTrophy) (*MsgMintTrophyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintTrophy not implemented")
}
func (*UnimplementedMsgServer) AssignTrophy(ctx context.Context, req *MsgAssignTrophy) (*MsgAssignTrophyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignTrophy not implemented")
}
func (*UnimplementedMsgServer) ReassignTrophy(ctx context.Context, req *MsgReassignTrophy) (*MsgReassignTrophyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReassignTrophy not implemented")
}
func (*UnimplementedMsgServer) RetireTrophy(ctx context.Context, req *MsgRetireTrophy) (*MsgRetireTrophyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetireTrophy not implemented")
}
func (*UnimplementedMsgServer) UpdateTrophyMetadata(ctx context.Context, req *MsgUpdateTrophyMetadata) (*MsgUpdateTrophyMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrophyMetadata not implemented")
}
func (*UnimplementedMsgServer) SetTrophyAuthority(ctx context.Context, req *MsgSetTrophyAuthority) (*MsgSetTrophyAuthorityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTrophyAuthority not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterTrophy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterTrophy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterTrophy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Msg/RegisterTrophy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterTrophy(ctx, req.(*MsgRegisterTrophy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MintTrophy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMintTrophy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MintTrophy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Msg/MintTrophy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MintTrophy(ctx, req.(*MsgMintTrophy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AssignTrophy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAssignTrophy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AssignTrophy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Msg/AssignTrophy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AssignTrophy(ctx, req.(*MsgAssignTrophy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ReassignTrophy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgReassignTrophy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ReassignTrophy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Msg/ReassignTrophy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ReassignTrophy(ctx, req.(*MsgReassignTrophy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RetireTrophy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRetireTrophy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RetireTrophy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Msg/RetireTrophy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RetireTrophy(ctx, req.(*MsgRetireTrophy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateTrophyMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateTrophyMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateTrophyMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Msg/UpdateTrophyMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateTrophyMetadata(ctx, req.(*MsgUpdateTrophyMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetTrophyAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetTrophyAuthority)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetTrophyAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wolochain.wartrophy.v1.Msg/SetTrophyAuthority",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetTrophyAuthority(ctx, req.(*MsgSetTrophyAuthority))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wolochain.wartrophy.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTrophy",
			Handler:    _Msg_RegisterTrophy_Handler,
		},
		{
			MethodName: "MintTrophy",
			Handler:    _Msg_MintTrophy_Handler,
		},
		{
			MethodName: "AssignTrophy",
			Handler:    _Msg_AssignTrophy_Handler,
		},
		{
			MethodName: "ReassignTrophy",
			Handler:    _Msg_ReassignTrophy_Handler,
		},
		{
			MethodName: "RetireTrophy",
			Handler:    _Msg_RetireTrophy_Handler,
		},
		{
			MethodName: "UpdateTrophyMetadata",
			Handler:    _Msg_UpdateTrophyMetadata_Handler,
		},
		{
			MethodName: "SetTrophyAuthority",
			Handler:    _Msg_SetTrophyAuthority_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wolochain/wartrophy/v1/tx.proto",
}

func (m *MsgRegisterTrophy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterTrophy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterTrophy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BountyGrowthPerDayUwolo != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BountyGrowthPerDayUwolo))
		i--
		dAtA[i] = 0x38
	}
	if m.TributePerDayUwolo != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TributePerDayUwolo))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ImageUri) > 0 {
		i -= len(m.ImageUri)
		copy(dAtA[i:], m.ImageUri)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ImageUri)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MetadataUri) > 0 {
		i -= len(m.MetadataUri)
		copy(dAtA[i:], m.MetadataUri)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MetadataUri)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DisplayName) > 0 {
		i -= len(m.DisplayName)
		copy(dAtA[i:], m.DisplayName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DisplayName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TrophyId) > 0 {
		i -= len(m.TrophyId)
		copy(dAtA[i:], m.TrophyId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TrophyId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterTrophyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterTrophyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterTrophyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgMintTrophy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMintTrophy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMintTrophy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TrophyId) > 0 {
		i -= len(m.TrophyId)
		copy(dAtA[i:], m.TrophyId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TrophyId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMintTrophyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMintTrophyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMintTrophyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAssignTrophy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAssignTrophy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAssignTrophy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TrophyId) > 0 {
		i -= len(m.TrophyId)
		copy(dAtA[i:], m.TrophyId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TrophyId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAssignTrophyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAssignTrophyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAssignTrophyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgReassignTrophy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgReassignTrophy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgReassignTrophy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewOwner) > 0 {
		i -= len(m.NewOwner)
		copy(dAtA[i:], m.NewOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewOwner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TrophyId) > 0 {
		i -= len(m.TrophyId)
		copy(dAtA[i:], m.TrophyId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TrophyId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgReassignTrophyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgReassignTrophyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgReassignTrophyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRetireTrophy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRetireTrophy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRetireTrophy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TrophyId) > 0 {
		i -= len(m.TrophyId)
		copy(dAtA[i:], m.TrophyId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TrophyId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRetireTrophyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRetireTrophyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRetireTrophyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateTrophyMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateTrophyMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateTrophyMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ImageUri) > 0 {
		i -= len(m.ImageUri)
		copy(dAtA[i:], m.ImageUri)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ImageUri)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MetadataUri) > 0 {
		i -= len(m.MetadataUri)
		copy(dAtA[i:], m.MetadataUri)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MetadataUri)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DisplayName) > 0 {
		i -= len(m.DisplayName)
		copy(dAtA[i:], m.DisplayName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DisplayName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TrophyId) > 0 {
		i -= len(m.TrophyId)
		copy(dAtA[i:], m.TrophyId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TrophyId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateTrophyMetadataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateTrophyMetadataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateTrophyMetadataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetTrophyAuthority) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetTrophyAuthority) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetTrophyAuthority) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewAuthority) > 0 {
		i -= len(m.NewAuthority)
		copy(dAtA[i:], m.NewAuthority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewAuthority)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetTrophyAuthorityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetTrophyAuthorityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetTrophyAuthorityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterTrophy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TrophyId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DisplayName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MetadataUri)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ImageUri)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TributePerDayUwolo != 0 {
		n += 1 + sovTx(uint64(m.TributePerDayUwolo))
	}
	if m.BountyGrowthPerDayUwolo != 0 {
		n += 1 + sovTx(uint64(m.BountyGrowthPerDayUwolo))
	}
	return n
}

func (m *MsgRegisterTrophyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgMintTrophy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TrophyId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgMintTrophyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAssignTrophy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TrophyId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAssignTrophyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgReassignTrophy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TrophyId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgReassignTrophyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRetireTrophy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TrophyId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRetireTrophyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateTrophyMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TrophyId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DisplayName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MetadataUri)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ImageUri)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateTrophyMetadataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetTrophyAuthority) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewAuthority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetTrophyAuthorityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterTrophy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterTrophy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterTrophy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrophyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrophyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImageUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImageUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TributePerDayUwolo", wireType)
			}
			m.TributePerDayUwolo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TributePerDayUwolo |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BountyGrowthPerDayUwolo", wireType)
			}
			m.BountyGrowthPerDayUwolo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BountyGrowthPerDayUwolo |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterTrophyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterTrophyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterTrophyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMintTrophy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMintTrophy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMintTrophy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrophyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrophyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMintTrophyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMintTrophyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMintTrophyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAssignTrophy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAssignTrophy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAssignTrophy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrophyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrophyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAssignTrophyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAssignTrophyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAssignTrophyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgReassignTrophy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgReassignTrophy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgReassignTrophy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrophyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrophyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgReassignTrophyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgReassignTrophyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgReassignTrophyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRetireTrophy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRetireTrophy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRetireTrophy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrophyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrophyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRetireTrophyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRetireTrophyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRetireTrophyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateTrophyMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateTrophyMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateTrophyMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrophyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrophyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImageUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImageUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateTrophyMetadataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateTrophyMetadataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateTrophyMetadataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetTrophyAuthority) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetTrophyAuthority: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetTrophyAuthority: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewAuthority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewAuthority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetTrophyAuthorityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetTrophyAuthorityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetTrophyAuthorityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
